var testData = {
  Authors: [
    {
      id: "1000",
      name: "Ursula K. Le Guin",
      nationality: "Amerikan",
      books: [
        {
          isbn: "9789753425285",
          title: "Mülksüzler",
          firstPublished: 1990,
          pageCount: 344,
          price: 124.8,
          currency: "TL",
          publisher: "Metis Yayınları",
          ratings: [
            { rate: 1, count: 1 },
            { rate: 2, count: 4 },
            { rate: 3, count: 15 },
            { rate: 4, count: 50 },
            { rate: 5, count: 105 },
          ],
        },
        {
          isbn: "9789753420570",
          title: "Yerdeniz Büyücüsü",
          firstPublished: 2007,
          pageCount: 1038,
          price: 77,
          currency: "TL",
          publisher: "İş Kültür Yayınları",
          ratings: [
            { rate: 1, count: 0 },
            { rate: 2, count: 14 },
            { rate: 3, count: 20 },
            { rate: 4, count: 130 },
            { rate: 5, count: 200 },
          ],
        },
      ],
    },
    {
      id: "1001",
      name: "Orhan Pamuk",
      nationality: "Türk",
      books: [
        {
          isbn: "9789750826702",
          title: "Sessiz Ev",
          firstPublished: 2013,
          pageCount: 296,
          price: 63,
          currency: "TL",
          publisher: "YKY",
          ratings: [
            { rate: 1, count: 0 },
            { rate: 2, count: 0 },
            { rate: 3, count: 10 },
            { rate: 4, count: 100 },
            { rate: 5, count: 250 },
          ],
        },
        {
          isbn: "9789750826139",
          title: "Kara Kitap",
          firstPublished: 2013,
          pageCount: 296,
          price: 63,
          currency: "TL",
          publisher: "YKY",
          ratings: [
            { rate: 1, count: 3 },
            { rate: 2, count: 5 },
            { rate: 3, count: 1 },
            { rate: 4, count: 120 },
            { rate: 5, count: 190 },
          ],
        },
      ],
    },
    {
      id: "1002",
      name: "George Orwell",
      nationality: "İngiliz",
      books: [
        {
          isbn: "9789750718533",
          title: "1984",
          firstPublished: "1984",
          pageCount: 352,
          price: 64,
          currency: "TL",
          publisher: "Can Yayınları",
          ratings: [
            { rate: 1, count: 0 },
            { rate: 2, count: 10 },
            { rate: 3, count: 23 },
            { rate: 4, count: 100 },
            { rate: 5, count: 1190 },
          ],
        },
        {
          isbn: "9789750719387",
          title: "Hayvan Çiftliği",
          firstPublished: "2001",
          pageCount: 152,
          price: 40,
          currency: "TL",
          publisher: "Can Yayınları",
          ratings: [
            { rate: 1, count: 34 },
            { rate: 2, count: 50 },
            { rate: 3, count: 230 },
            { rate: 4, count: 120 },
            { rate: 5, count: 590 },
          ],
        },
      ],
    },
    {
      id: "1003",
      name: "Louis-Ferdinand Céline",
      nationality: "Fransız",
      books: [
        {
          isbn: "9789750804198",
          title: "Gecenin Sonuna Yolculuk",
          firstPublished: 2002,
          pageCount: 536,
          price: 66.5,
          currency: "TL",
          publisher: "YKY",
          ratings: [
            { rate: 1, count: 23 },
            { rate: 2, count: 30 },
            { rate: 3, count: 20 },
            { rate: 4, count: 310 },
            { rate: 5, count: 390 },
          ],
        },
      ],
    },
    {
      id: "1004",
      name: "Fyodor Mihayloviç Dostoyevski",
      nationality: "Rus",
      books: [
        {
          isbn: "9789754589023",
          title: "Suç ve Ceza",
          firstPublished: 2006,
          pageCount: 704,
          price: 56,
          currency: "TL",
          publisher: "İş Kültür Yayınları",
          ratings: [
            { rate: 1, count: 0 },
            { rate: 2, count: 3 },
            { rate: 3, count: 50 },
            { rate: 4, count: 310 },
            { rate: 5, count: 6090 },
          ],
        },
        {
          isbn: "9789944880985",
          title: "Karamazov Kardeşler",
          firstPublished: 2007,
          pageCount: 1038,
          price: 77,
          currency: "TL",
          publisher: "İş Kültür Yayınları",
          ratings: [
            { rate: 1, count: 4 },
            { rate: 2, count: 77 },
            { rate: 3, count: 40 },
            { rate: 4, count: 720 },
            { rate: 5, count: 5090 },
          ],
        },
      ],
    },
  ],
  Discounts: [
    {
      isbn: "9789753425285",
      discount: 20,
    },
    {
      isbn: "9789753420570",
      discount: 15,
    },
    {
      isbn: "9789750826702",
      discount: 5,
    },
    {
      isbn: "9789750826139",
      discount: 20,
    },
    {
      isbn: "9789750718533",
      discount: 35,
    },
    {
      isbn: "9789750804198",
      discount: 25,
    },
    {
      isbn: "9789754589023",
      discount: 10,
    },
    {
      isbn: "9789944880985",
      discount: 45,
    },
  ],
};
